# Forked from the Jekyll Resume Theme by Matt Couchman

# Site settings
title: Nathan Karasch | Software Engineering Student
email: nkarasch@iastate.edu
description: Rock Drummer turned US Marine turned Software Engineering student.
baseurl: ""
url: "http://nkarasch.public.iastate.edu/"
name: Nathan Karasch
job: Software Engineering Student
location: Iowa State University
profile_image: "img/nathankarasch-scaled.jpg"
languages: HTML, CSS and Javascript   # TODO
email_address: nkarasch@iastate.edu
github_username:  KrashLeviathan
linkedin_username:  nathankarasch

# Build settings
markdown: kramdown
